# File: export_utils.py
# Utility functions for exporting reports in various formats

import os
from datetime import datetime
import pandas as pd
from database import load_data


def export_sales_excel(start_date=None, end_date=None, output_dir='exports'):
    """
    Export sales data to Excel format.
    
    Args:
        start_date: Start date filter (optional)
        end_date: End date filter (optional)
        output_dir: Directory to save the export file
    
    Returns:
        str: Path to the generated Excel file
    """
    try:
        # Create exports directory if it doesn't exist
        if not os.path.exists(output_dir):
            os.makedirs(output_dir)
        
        # Load transaction data
        df = load_data('transactions')
        
        # Convert date column to datetime
        df['date'] = pd.to_datetime(df['date'])
        
        # Apply date filters if provided
        if start_date:
            df = df[df['date'] >= pd.to_datetime(start_date)]
        if end_date:
            df = df[df['date'] <= pd.to_datetime(end_date)]
        
        # Generate filename with timestamp
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        filename = f'sales_export_{timestamp}.xlsx'
        filepath = os.path.join(output_dir, filename)
        
        # Create Excel writer with multiple sheets
        with pd.ExcelWriter(filepath, engine='openpyxl') as writer:
            # Main data sheet
            df.to_excel(writer, sheet_name='Sales Data', index=False)
            
            # Summary statistics sheet
            summary = df.groupby('product').agg({
                'quantity': ['sum', 'mean', 'count'],
                'price': ['mean', 'min', 'max']
            }).round(2)
            summary.to_excel(writer, sheet_name='Summary Statistics')
            
            # Daily sales sheet
            daily = df.groupby([df['date'].dt.date, 'product']).agg({
                'quantity': 'sum',
                'price': 'mean'
            }).reset_index()
            daily.to_excel(writer, sheet_name='Daily Sales', index=False)
        
        return filepath
    
    except Exception as e:
        raise RuntimeError(f"Failed to export Excel: {str(e)}")


def generate_forecast_pdf(product, forecast_data, output_dir='exports'):
    """
    Generate a PDF report for forecast data.
    
    Args:
        product: Product name
        forecast_data: DataFrame with forecast results
        output_dir: Directory to save the PDF
    
    Returns:
        str: Path to the generated PDF file
    """
    try:
        # This is a placeholder - full PDF generation would require reportlab
        # For now, we'll create a simple text report
        
        if not os.path.exists(output_dir):
            os.makedirs(output_dir)
        
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        filename = f'forecast_{product}_{timestamp}.txt'
        filepath = os.path.join(output_dir, filename)
        
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(f"=== Demand Forecast Report ===\n")
            f.write(f"Product: {product}\n")
            f.write(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
            f.write(f"{'='*50}\n\n")
            
            if hasattr(forecast_data, 'to_string'):
                f.write(forecast_data.to_string())
            else:
                f.write(str(forecast_data))
            
            f.write(f"\n\n{'='*50}\n")
            f.write(f"Report generated by AI-First Commerce Engine\n")
        
        return filepath
    
    except Exception as e:
        raise RuntimeError(f"Failed to generate PDF: {str(e)}")


def export_comparison_report(products, output_dir='exports'):
    """
    Generate a comparison report for multiple products.
    
    Args:
        products: List of product names to compare
        output_dir: Directory to save the report
    
    Returns:
        str: Path to the generated file
    """
    try:
        if not os.path.exists(output_dir):
            os.makedirs(output_dir)
        
        # Load all transaction data
        df = load_data('transactions')
        
        # Filter for specified products
        df_filtered = df[df['product'].isin(products)]
        
        # Generate comparison statistics
        comparison = df_filtered.groupby('product').agg({
            'quantity': ['sum', 'mean', 'std'],
            'price': ['mean', 'std']
        }).round(2)
        
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        filename = f'product_comparison_{timestamp}.xlsx'
        filepath = os.path.join(output_dir, filename)
        
        with pd.ExcelWriter(filepath, engine='openpyxl') as writer:
            comparison.to_excel(writer, sheet_name='Comparison')
            
            # Individual product sheets
            for product in products:
                product_data = df_filtered[df_filtered['product'] == product]
                product_data.to_excel(writer, sheet_name=product[:30], index=False)
        
        return filepath
    
    except Exception as e:
        raise RuntimeError(f"Failed to generate comparison report: {str(e)}")
